"""updated login spel

Revision ID: 500d4b5a40e8
Revises: e1bd34a3b7f9
Create Date: 2026-01-21 20:54:01.795492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '500d4b5a40e8'
down_revision: Union[str, Sequence[str], None] = 'e1bd34a3b7f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'refresh_token', ['id'])
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'last_loggin_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_loggin_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_login_at')
    op.drop_constraint(None, 'refresh_token', type_='unique')
    # ### end Alembic commands ###
