"""added password reset token table

Revision ID: e104023d250d
Revises: d25b805e2c31
Create Date: 2026-01-24 16:17:27.897076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e104023d250d'
down_revision: Union[str, Sequence[str], None] = 'd25b805e2c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hashed_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_hashed_token'), 'password_reset_tokens', ['hashed_token'], unique=True)
    op.add_column('users', sa.Column('password_reset_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_reseted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reseted_at')
    op.drop_column('users', 'password_reset_sent_at')
    op.drop_index(op.f('ix_password_reset_tokens_hashed_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
